/* DO NOT EDIT THIS FILE - it is machine generated */
#include "io_leveldb_android_LevelIterator.h"
#include "util.h"
/* Header for class io_leveldb_android_LevelIterator */
/*
 * Class:     io_leveldb_android_LevelIterator
 * Method:    destory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_leveldb_android_LevelIterator_destory(JNIEnv *env, jclass, jlong ptr)
{
  leveldb::Iterator *iter = reinterpret_cast<leveldb::Iterator *>(ptr);

  delete iter;
}

/*
 * Class:     io_leveldb_android_LevelIterator
 * Method:    seekToFirst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_leveldb_android_LevelIterator_seekToFirst(JNIEnv *, jclass, jlong iterPtr)
{
  leveldb::Iterator *iter = reinterpret_cast<leveldb::Iterator *>(iterPtr);
  iter->SeekToFirst();
}

/*
 * Class:     io_leveldb_android_LevelIterator
 * Method:    seekToLast
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_leveldb_android_LevelIterator_seekToLast(JNIEnv *, jclass, jlong iterPtr)
{
  leveldb::Iterator *iter = reinterpret_cast<leveldb::Iterator *>(iterPtr);
  iter->SeekToLast();
}

/*
 * Class:     io_leveldb_android_LevelIterator
 * Method:    seek
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_io_leveldb_android_LevelIterator_seek(JNIEnv *env, jclass, jlong iterPtr, jbyteArray keyObj)
{
  leveldb::Iterator *iter = reinterpret_cast<leveldb::Iterator *>(iterPtr);

  size_t keyLen = env->GetArrayLength(keyObj);
  jbyte *buffer = env->GetByteArrayElements(keyObj, NULL);

  iter->Seek(leveldb::Slice((const char *)buffer, keyLen));
  env->ReleaseByteArrayElements(keyObj, buffer, JNI_ABORT);
}

/*
 * Class:     io_leveldb_android_LevelIterator
 * Method:    valid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_leveldb_android_LevelIterator_valid(JNIEnv *, jclass, jlong iterPtr)
{
  leveldb::Iterator *iter = reinterpret_cast<leveldb::Iterator *>(iterPtr);
  return iter->Valid();
}

/*
 * Class:     io_leveldb_android_LevelIterator
 * Method:    next
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_leveldb_android_LevelIterator_next(JNIEnv *, jclass, jlong iterPtr)
{

  leveldb::Iterator *iter = reinterpret_cast<leveldb::Iterator *>(iterPtr);
  iter->Next();
}

/*
 * Class:     io_leveldb_android_LevelIterator
 * Method:    prev
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_leveldb_android_LevelIterator_prev(JNIEnv *, jclass, jlong iterPtr)
{
  leveldb::Iterator *iter = reinterpret_cast<leveldb::Iterator *>(iterPtr);
  iter->Prev();
}

/*
 * Class:     io_leveldb_android_LevelIterator
 * Method:    key
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_leveldb_android_LevelIterator_key(JNIEnv *env, jclass, jlong iterPtr)
{
  leveldb::Iterator *iter = reinterpret_cast<leveldb::Iterator *>(iterPtr);
  leveldb::Slice key = iter->key();
  size_t len = key.size();
  jbyteArray result = env->NewByteArray(len);
  env->SetByteArrayRegion(result, 0, len, (const jbyte *)key.data());
  return result;
}

/*
 * Class:     io_leveldb_android_LevelIterator
 * Method:    value
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_leveldb_android_LevelIterator_value(JNIEnv *env, jclass, jlong iterPtr)
{
  leveldb::Iterator *iter = reinterpret_cast<leveldb::Iterator *>(iterPtr);
  leveldb::Slice value = iter->value();

  size_t len = value.size();
  jbyteArray result = env->NewByteArray(len);
  env->SetByteArrayRegion(result, 0, len, (const jbyte *)value.data());
  return result;
}
