/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_leveldb_android_LevelDB */

#ifndef _Included_io_leveldb_android_LevelDB
#define _Included_io_leveldb_android_LevelDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_leveldb_android_LevelDB
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_leveldb_android_LevelDB_nativeOpen
  (JNIEnv *, jobject, jstring);
  JNIEXPORT void JNICALL Java_io_leveldb_android_LevelDB_repair
    (JNIEnv *, jobject, jstring);

/*
 * Class:     io_leveldb_android_LevelDB
 * Method:    close
 * Signature: (J)J
 */
JNIEXPORT void JNICALL Java_io_leveldb_android_LevelDB_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_leveldb_android_LevelDB
 * Method:    put
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_io_leveldb_android_LevelDB_put
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     io_leveldb_android_LevelDB
 * Method:    get
 * Signature: (JJ[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_leveldb_android_LevelDB_get__JJ_3B
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     io_leveldb_android_LevelDB
 * Method:    get
 * Signature: (JJLjava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_leveldb_android_LevelDB_get__JJLjava_nio_ByteBuffer_2
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     io_leveldb_android_LevelDB
 * Method:    delete
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_io_leveldb_android_LevelDB_delete
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_leveldb_android_LevelDB
 * Method:    write
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_leveldb_android_LevelDB_write
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_leveldb_android_LevelDB
 * Method:    destory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_leveldb_android_LevelDB_destory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_leveldb_android_LevelDB
 * Method:    iterator
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_leveldb_android_LevelDB_iterator
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_leveldb_android_LevelDB
 * Method:    getSnapshot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_leveldb_android_LevelDB_getSnapshot
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_leveldb_android_LevelDB
 * Method:    releseSnapshot
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_leveldb_android_LevelDB_releseSnapshot
  (JNIEnv *, jclass, jlong, jlong);
 JNIEXPORT void JNICALL Java_io_leveldb_android_LevelDB_initLevelDB
    (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
